DROP TABLE credentials
IF EXISTS;
DROP TABLE configuration
IF EXISTS;

CREATE TABLE credentials (
  user_id    INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1
  INCREMENT BY 1 ) PRIMARY KEY,
  email_id   VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name  VARCHAR(50) NOT NULL,
  password   VARCHAR(50) NOT NULL
);

CREATE TABLE configuration (
  config_id    INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1
  INCREMENT BY 1 ) PRIMARY KEY,
  config_key   VARCHAR(255)                        NOT NULL,
  config_value VARCHAR(255),
  create_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);